//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int id { get; set; }
        public int id_exam { get; set; }
        public string id_etudiant { get; set; }
        public decimal note_exam { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        public virtual Etudiant Etudiant1 { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
